name: real_beez
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI and general dependencies
  cupertino_icons: ^1.0.8
  pin_code_fields: ^8.0.1
  smooth_page_indicator: ^1.1.0
  flutter_custom_clippers: ^2.1.0
  flutter_svg: ^2.0.9
  video_player: ^2.6.0
  table_calendar: ^3.1.2
  google_fonts: ^6.1.0
  shared_preferences: ^2.3.2
  carousel_slider: ^4.2.1
  chewie: ^1.7.5
  http: ^1.1.0
  flutter_screenutil: ^5.9.0
  shimmer: ^3.0.0
  flutter_dotenv: ^5.1.0


  # Location & maps
  google_maps_flutter: ^2.13.1
  geolocator: ^11.1.0

  flutter_riverpod: ^2.5.1
  google_generative_ai: ^0.4.0
  flutter_markdown: ^0.7.3
  scroll_to_index: ^2.1.1


  maplibre_gl:
    git:
      url: https://github.com/m0nac0/flutter-maplibre-gl.git
      ref: main
      path: maplibre_gl

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  flutter_launcher_icons: ^0.14.4   

flutter_icons:
  android: true                   
  ios: true
  image_path: "assets/logo/bee.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/icons/
    - assets/images/
    - assets/videos/
    - static_data.json
